version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: college_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: collegeplatform

  backend:
    build: ./backend
    container_name: college_backend
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/collegeplatform
      PORT: 5000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: college_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
